--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/LemonTPA
build-by-default: true
branches:
- main
projects:
  LemonTPA:
    path: ""
    libs:
       - src: ACM-PocketMine-MP/Commando/Commando
         version: ^3.2.1
       - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
         version: ^1.0.0
    lint: false
...
